### ISSUE TITLE
Bounty Hunter issue

### ISSUE THREAD

**Issue by Ruichka** [Mastagoon/untrusted-discord#5]
When you attempt to find Bounty Hunter via `/class`, the app fails (with an error instead of "No class found")

I suspect the line `"night_skills": ["Doxx and Stalk", "Frame", "Citizen's Arrest"]` in `data/classData.json`. In this line, it uses a skill named "Citizen's Arrest". However, in `data/skillData.json` it is called `Citizen&#039;s arrest`.

**Comment by Mastagoon** [comment]
I can confirm the app crashes. It seems it can't find one of the bounty hunter skills in the skill json we have. A temporary solution would be to add a check if the skill exists before we return it, as well as changing the skill name manually.
A better solution would be if knu returned the skill ID instead of their names in the class APIs
